# Supabase credentials
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_KEY = "your-supabase-key"

# Optional Dropbox settings
# DROPBOX_API_TOKEN = "..."
# DROPBOX_REFRESH_TOKEN = "..."
# DROPBOX_APP_KEY = "..."
# DROPBOX_APP_SECRET = "..."
# DROPBOX_FOLDER_PATH = "receipts"
